name: Minibits JS bundle code push

# This workflow is manually triggered. 
on: workflow_dispatch

jobs:
  deploy-code-push:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
    # Fetch the version in our package.json file
      - name: Get JS bundle version
        id: version-reader-js
        uses: koj-co/package-version-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Get Android native version
        id: version-reader-androidd
        uses: Devofure/version-reader-action@v1
        with:
          gradlePath: app/build.gradle
          
      # Create .env file      
      - name: Generate .env
        run: |-
          echo APP_ENV='PROD' >> .env
          echo LOG_LEVEL='INFO' >> .env
          echo SENTRY_ACTIVE='TRUE' >> .env
          echo SENTRY_DSN='${{ secrets.SENTRY_DSN }}' >> .env
          echo CODEPUSH_KEY_ANDROID='${{ secrets.CODEPUSH_KEY_ANDROID }}' >> .env
          echo NATIVE_VERSION_ANDROID='${{ steps.version-reader-android.outputs.versionName }}' >> .env
          echo JS_BUNDLE_VERSION='${{ steps.version-reader-js.outputs.package-version }}' >> .env
          echo COMMIT='${{ steps.version-reader-js.outputs.short-hash }}' >> .env    
          
      - name: Install app dependencies
        uses: bahmutov/npm-install@v1       
          
      # Required!
      - name: Install AppCenter CLI
        run: npm install -g appcenter-cli
        
      - name: Deploy to CodePush Android
        run: appcenter codepush release-react -a minibits-cash/minibits_wallet_android -d Production
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN_ANDROID }}
          
      - name: Create version tag
        run: git tag ${{ steps.version-reader-js.outputs.package-version }}
        
      - name: Push new tag to remote
        run: git push origin ${{ steps.version-reader-js.outputs.package-version}}